# 重命名脚本

# docs目录下的文档重命名
Rename-Item "Kinlin-AI技术文档-03-创新功能详解.md" "03-创新功能详解-Innovation-Features.md"
Rename-Item "Kinlin-AI技术文档-04-部署和运维指南.md" "04-部署运维指南-Deployment-Operations.md"
Rename-Item "Kinlin-AI技术文档-05-API接口文档.md" "05-API接口文档-API-Documentation.md"
Rename-Item "Kinlin-AI技术文档-06-联邦学习专题.md" "06-联邦学习专题-Federated-Learning.md"
Rename-Item "Kinlin-AI技术文档-索引.md" "索引-Index.md"
Rename-Item "快速开始-麒麟SDK和增强RAG.md" "快速开始-麒麟SDK和增强RAG-Quick-Start.md"
Rename-Item "数字人图像加载修复说明.md" "数字人图像加载修复-Digital-Human-Image-Fix.md"
Rename-Item "数字人形象保存说明.md" "数字人形象保存-Digital-Human-Profile-Save.md"
Rename-Item "数字人语音对话-修复完成说明.md" "数字人语音对话修复-Digital-Human-Voice-Fix.md"
Rename-Item "数字人路径配置说明.md" "数字人路径配置-Digital-Human-Path-Config.md"
Rename-Item "更新说明-2025-01-03-麒麟SDK与RAG增强.md" "更新说明-2025-01-03-麒麟SDK与RAG增强-Update-Notes.md"
Rename-Item "知识库按角色分类使用说明.md" "知识库按角色分类-Knowledge-Base-Role-Classification.md"
Rename-Item "联邦学习全局最优模型-使用指南.md" "联邦学习全局最优模型使用指南-Federated-Learning-Global-Model-Guide.md"
Rename-Item "联邦学习全局最优模型-可行性分析与实现方案.md" "联邦学习全局最优模型可行性分析-Federated-Learning-Feasibility-Analysis.md"
Rename-Item "联邦学习全局最优模型-实现完成报告.md" "联邦学习全局最优模型实现报告-Federated-Learning-Implementation-Report.md"
Rename-Item "联邦学习全局最优模型-快速开始.md" "联邦学习全局最优模型快速开始-Federated-Learning-Quick-Start.md"
Rename-Item "联邦学习全局最优模型-总结报告.md" "联邦学习全局最优模型总结报告-Federated-Learning-Summary-Report.md"
Rename-Item "联邦学习全局最优模型-最终版本说明.md" "联邦学习全局最优模型最终版本-Federated-Learning-Final-Version.md"
Rename-Item "语音对话功能-完整实现说明.md" "语音对话功能完整实现-Voice-Dialog-Implementation.md"
Rename-Item "问题修复指南-ChromaDB和Pydantic.md" "问题修复指南-ChromaDB和Pydantic-Issue-Fix-Guide.md"
Rename-Item "麒麟AI_API使用说明.md" "麒麟AI_API使用说明-Kinlin-AI-API-Guide.md"
Rename-Item "麒麟SDK与RAG增强-实现总结.md" "麒麟SDK与RAG增强实现总结-Kinlin-SDK-RAG-Summary.md"
Rename-Item "麒麟SDK智能切换与增强RAG指南.md" "麒麟SDK智能切换与增强RAG指南-Kinlin-SDK-Smart-Switch-RAG-Guide.md"