import asyncio
import importlib
from typing import Any, Dict, List
from unittest.mock import patch

from app.agent_core.react.planner import ReactPlanner
from app.agent_core.schema.agent_types import AgentWriterRequest, SkillRequest
from app.agent_core.skills.writer import (
    CharacterRelationSkill,
    ContentWriteSkill,
    InspirationExpandSkill,
    OutlineGenerateSkill,
)
from app.api import agent_writer


class FakeAIService:
    async def generate_text(self, text: str, role_id: str = None, context: List[Dict[str, str]] = None, **kwargs) -> Dict[str, Any]:
        prompt = text or ""
        lowered = prompt.lower()

        if "creative_tree" in lowered or "inspiration" in lowered:
            return {
                "text": (
                    '{"creative_tree":{"id":"root","label":"Time Traveler Story","description":"core premise",'
                    '"children":[{"id":"root.world","label":"World","description":"future dystopia","children":[]},'
                    '{"id":"root.hero","label":"Hero","description":"engineer protagonist","children":[]}]}}'
                )
            }
        if "outline" in lowered and "chapter" in lowered:
            return {
                "text": (
                    "# Story Outline\n\n## Core Idea\nTime traveler prevents collapse.\n\n"
                    "## Chapter 1\n- Goal: Introduce conflict\n- Key event: Failed rescue\n- Emotional beat: Fear\n\n"
                    "## Chapter 2\n- Goal: Build alliance\n- Key event: Mentor appears\n- Emotional beat: Hope\n"
                )
            }
        if "relation_graph" in lowered or "relationship graph" in lowered:
            return {
                "text": (
                    '{"relation_graph":{"nodes":[{"id":"A","label":"A","group":"protagonist"},'
                    '{"id":"B","label":"B","group":"antagonist"}],'
                    '"edges":[{"from":"A","to":"B","label":"conflict"}]}}'
                )
            }
        if "fiction writer" in lowered or "chapter" in lowered:
            return {"text": "Chapter text generated by fake model."}

        return {"text": "{}"}


def _build_request(text: str, action_input: Dict[str, Any]) -> SkillRequest:
    return SkillRequest(
        sessionId="writer-test-session",
        text=text,
        actionInput=action_input,
        memory={"history": [{"role": "user", "content": text}]},
    )


async def _assert_timeout_fallback(skill, request: SkillRequest) -> None:
    module = importlib.import_module(skill.__class__.__module__)

    async def _timeout_wait_for(coro, timeout):
        try:
            coro.close()
        except Exception:
            pass
        raise asyncio.TimeoutError

    with patch.object(module.asyncio, "wait_for", new=_timeout_wait_for):
        result = await skill.run(request)
    assert result.success is True
    assert "timeout" in result.message.lower()


async def test_inspiration_expand_skill():
    skill = InspirationExpandSkill(ai_service=FakeAIService())
    request = _build_request("time traveler saves world", {"premise": "time traveler saves world"})
    result = await skill.run(request)
    assert result.success is True
    assert "creative_tree" in result.output
    await _assert_timeout_fallback(skill, request)


async def test_outline_generate_skill():
    skill = OutlineGenerateSkill(ai_service=FakeAIService())
    request = _build_request(
        "generate outline",
        {"creative_selection": "time traveler saves world", "chapters_count": 6},
    )
    result = await skill.run(request)
    assert result.success is True
    assert "outline_markdown" in result.output
    await _assert_timeout_fallback(skill, request)


async def test_content_write_skill():
    skill = ContentWriteSkill(ai_service=FakeAIService())
    request = _build_request(
        "write chapter",
        {
            "outline_context": "Chapter 1 introduces conflict",
            "chapter_index": 1,
            "style": "Lu Xun style",
        },
    )
    result = await skill.run(request)
    assert result.success is True
    assert "content" in result.output
    await _assert_timeout_fallback(skill, request)


async def test_character_relation_skill():
    skill = CharacterRelationSkill(ai_service=FakeAIService())
    request = _build_request(
        "build relation graph",
        {
            "story_description": "A confronts B in a dystopian city",
            "character_list": ["A", "B"],
        },
    )
    result = await skill.run(request)
    assert result.success is True
    graph = result.output.get("relation_graph", {})
    assert isinstance(graph.get("nodes", []), list)
    assert isinstance(graph.get("edges", []), list)
    await _assert_timeout_fallback(skill, request)


async def test_writer_planner():
    planner = ReactPlanner()
    plan = planner.plan("帮我写一个时间旅行故事并给人物关系图", history=[], role="writer")
    actions = [item.action for item in plan]
    assert "inspiration_expand" in actions
    assert "outline_generate" in actions
    assert "content_write" in actions
    assert "character_relation_map" in actions


async def test_writer_route():
    fake_ai = FakeAIService()

    original_writer_skills = dict(agent_writer.tool_router.skills_by_role.get("writer", {}))
    original_ai_service = agent_writer.ai_service
    try:
        agent_writer.tool_router.register_skills_for_role(
            "writer",
            {
                "inspiration_expand": InspirationExpandSkill(ai_service=fake_ai),
                "outline_generate": OutlineGenerateSkill(ai_service=fake_ai),
                "content_write": ContentWriteSkill(ai_service=fake_ai),
                "character_relation_map": CharacterRelationSkill(ai_service=fake_ai),
            },
        )
        agent_writer.ai_service = fake_ai

        response = await agent_writer.writer_agent_chat(
            AgentWriterRequest(text="我想写一个时间旅行者拯救世界的故事")
        )
        assert response.success is True
        assert len(response.skills_used) > 0
        assert response.inspiration_expand is not None
    finally:
        agent_writer.tool_router.register_skills_for_role("writer", original_writer_skills)
        agent_writer.ai_service = original_ai_service


async def _main():
    await test_inspiration_expand_skill()
    print("[PASS] inspiration_expand")
    await test_outline_generate_skill()
    print("[PASS] outline_generate")
    await test_content_write_skill()
    print("[PASS] content_write")
    await test_character_relation_skill()
    print("[PASS] character_relation_map")
    await test_writer_planner()
    print("[PASS] writer_planner")
    await test_writer_route()
    print("[PASS] writer_route")


if __name__ == "__main__":
    asyncio.run(_main())
